# Generated by Django 5.2.7 on 2025-11-12 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellido')),
                ('Job', models.CharField(choices=[('1', 'ADMINISTRADOR'), ('0', 'CONTADOR'), ('3', 'OTRO'), ('2', 'ECONOMISTA')], max_length=50, verbose_name='Trabajo')),
                ('departamemto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
            ],
        ),
    ]
