# Generated by Django 5.2.7 on 2026-01-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_empleado_full_name'),
        ('personas', '0005_empleado_avatar'),
    ]

    operations = [
    ]
